Prettifier for datetimes
CS2103AUG2016-F11-C3/main pull request #58
Opened 2016-10-25 11:48 UTC by darrenwee

# For @yyc /whoever is doing UI
You should only use the `extractPretty...` methods in `Item` and not have to touch the static methods in `DateTimeParser`.

For making the datetime string in the Item card, use the `Item.extractPrettyItemCardDateTime()` method. Literally just print whatever comes out of that method. It can return an empty string if the `Item` has nulls for `startDate` and `endDate`. It can take the following forms:
```bash
# if start/end are within two weeks from system time
This Monday, 9:30PM
This Saturday, 9:30PM - 10:30PM
Next Monday, 9:30PM
Next Saturday, 9:30PM - 10:30PM
This Sunday, 10:31AM - Next Monday, 7:30PM

# if start/end are at least two weeks away from system time
Sun 25 Dec, 4:31AM
Sun 25 Dec, 12:37AM - Tue 27 Dec, 10:00PM

# if start and end dates are at least a year apart 
Sun 25 Dec 2016, 12:37AM - Tue 27 Dec 2017, 10:00PM
```

For making the relative date, use `Item.extractPrettyRelativeEndDateTime()`. It can take the following forms:
```bash
# for dates in the future
moments from now
3 minutes from now
2 days from now
1 week from now
1 month from now

# for dates in the past
moments ago
3 minutes ago
2 days ago
1 week ago
1 month ago
```

2016-10-26 12:55 UTC, yyc commented
I've added the necessary UI changes, might make debugging easier on your end.
Right now a couple of issues: Can dates today be "Today" instead of "This Wednesday"

Also, all tasks currently have start times. We're planning to fix that, so it needs to be able to handle instances where the startDate or endDate is null.

2016-10-26 13:00 UTC, yyc requested changes
I've added the necessary UI changes, might make debugging easier on your end.

Right now a couple of issues: Can dates today be "Today" instead of "This Wednesday"

Also, all tasks currently have start times. We're planning to fix that, so it needs to be able to handle instances where the startDate or endDate is null.

2016-10-27 08:23 UTC, darrenwee commented
> Can dates today be "Today" instead of "This Wednesday"

Fixed. Also implemented dates for "Tomorrow".

> Also, all tasks currently have start times. We're planning to fix that, so it needs to be able to handle instances where the startDate or endDate is null.

I changed the behaviour of `DateTimeParser.extractEndDate` to return a `null` if there isn't exactly two datetime tokens in the input (e.g. `add "walk dog" at 5pm today` has one datetime token as opposed to `add "walk dog" from 5-6pm today` which has two). This will cause input with *exactly* one date token to only fill the `Item.startDate` and leave `Item.endDate` as `null`. At least for v0.4, we do not distinguish `Item`s with only the start date or only the end date (I can't do this easily without fixing certain keywords like "at" or "by" in the datetime fields of the relevant commands anyway, so we may have to leave it implemented this way). FYI @acuodancer @craaaa

The prettifier now handles tasks with a single datetime too, e.g. `add "walk dog" at 5pm` or `add "finish 2103 essay" by today 2359h`.

2016-10-27 12:40 UTC, yyc approved these changes

2016-10-27 15:34 UTC, yyc commented
Ideally the dates should change, but that's currently not supported because it's not that easy to do.
I'm merging this in anyway, so that small issue (opened #62) doesn't block this feature for 0.4.

2016-10-27 15:34 UTC, merged